#cloud-config

coreos:
  update:
    reboot-strategy: "off"
  etcd2:
    name: {{ETCD_NODE_NAME}}
    initial-cluster: {{ETCD_INITIAL_CLUSTER}}
    advertise-client-urls: http://127.0.0.1:2379
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster-token: vagrant-etcd-cluster
    initial-cluster-state: new
  units:
    - name: etcd2.service
      command: start
