
coreos:
  update:
    reboot-strategy: "off"
  units:
    - name: docker.service
      command: start
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop
