#cloud-config

hostname: master1

coreos:
  update:
    reboot-strategy: off
  units:
    - name: sshd.service
      command: start
    - name: flanneld.service
      command: stop
      command: start
    - name: update-engine.service
      command: stop
    - name: locksmithd.service
      command: stop

users:
  - name: batazor
    passwd: $6$SALT$3MUMz4cNIRjQ/Knnc3gXjJLV1vdwFs2nLvh//nGtEh/.li04NodZJSfnc4jeCVHd7kKHGnq5MsenN.tO6Z.Cj/ #password
    groups:
    - sudo
    - docker

write_files:
- path: "/etc/resolv.conf"
  permissions: "0644"
  owner: "root"
  content: |
    nameserver 8.8.8.8
